### ISSUE TITLE
Autocomple / pw managers (e.g: bitwarden) are not supported in the contact form

### ISSUE THREAD

**Issue by Sinnamoon** [t-rosa/www.janedoagency.com#6]
like if you try to fill you name, num, last name, email quickly unless you click on the fields after autocomplete they wont be taken into account
<img src="https://media.tenor.com/jUMex_rdqPwAAAAM/among-us-twerk.gif">

**Comment by t-rosa** [comment]
Contact page will be replace by wizard form
